services:
  database-accessor-api:
    container_name: database-accessor-api
    build: 
      context: ./database-accessor-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./database-accessor-api:/app
    depends_on:
      - timescaledb
    env_file:
      - .env
    restart: always

  indicator-api:
    container_name: indicator-api
    build: 
      context: ./indicator-api
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    volumes:
      - ./indicator-api:/app
    depends_on:
      - database-accessor-api
    env_file:
      - .env
    restart: always

  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./timescaledb-init:/docker-entrypoint-initdb.d

  broker-service:
    container_name: broker-service
    build:
      context: ./broker-service
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - ./broker-service:/app
    depends_on:
      - redis
    env_file:
      - .env
    restart: always

  ingestion-service:
    container_name: ingestion-service
    build:
      context: ./ingestion-service
      dockerfile: Dockerfile
    volumes:
      - ./ingestion-service:/app
    depends_on:
      - timescaledb
      - broker-service
      - redis
    env_file:
      - .env
    restart: always

  webserver:
    container_name: webserver
    build:
      context: ./webserver
      dockerfile: Dockerfile
    ports:
      - 8765:8765
    volumes:
      - ./webserver:/app
    depends_on:
      - redis
      - broker-service
    env_file:
      - ./webserver/.env
    environment:
      - MODE=${MODE}
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - frontend_data:/app/dist
      - ./frontend:/app/frontend    
    depends_on:
      - webserver
    environment:
      - MODE=${MODE}

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always

volumes:
  timescaledb_data:
  frontend_data:
  redis_data:

