"""Domain package exports."""

from .enums import (
    BacktestEngine,
    DataGranularity,
    ExitReason,
    FillTiming,
    GapPolicy,
    IntrabarExitPolicy,
    MarketEventType,
    OrderSide,
    PositionSide,
    PriceSource,
    SignalTiming,
    TradeAccountingPolicy,
)
from .events import BarEvent, TickEvent
from .types import (
    BacktestRequest,
    BacktestResult,
    BarView,
    ExecutionArrayBundle,
    ExecutionConfig,
    FeatureMatrix,
    Fill,
    PortfolioSnapshot,
    PortfolioView,
    PositionView,
    ProtectiveExitSpec,
    SignalMatrix,
    StrategyConfig,
    TickView,
    Trade,
)

__all__ = [
    "BacktestRequest",
    "BacktestEngine",
    "BacktestResult",
    "BarEvent",
    "BarView",
    "DataGranularity",
    "ExecutionArrayBundle",
    "ExecutionConfig",
    "ExitReason",
    "FeatureMatrix",
    "Fill",
    "FillTiming",
    "GapPolicy",
    "IntrabarExitPolicy",
    "MarketEventType",
    "OrderSide",
    "PortfolioSnapshot",
    "PortfolioView",
    "PositionSide",
    "PositionView",
    "PriceSource",
    "ProtectiveExitSpec",
    "SignalMatrix",
    "SignalTiming",
    "StrategyConfig",
    "TickEvent",
    "TickView",
    "Trade",
    "TradeAccountingPolicy",
]
