-- A turn is one standalone run or one eligible batch, independent of batch size.
-- The identity sequence is durable and never reused, including across restarts.
CREATE TABLE backtest_queue_turns (
    turn_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id VARCHAR(36) REFERENCES backtest_runs(run_id) ON DELETE CASCADE,
    batch_id VARCHAR(36) REFERENCES backtest_batches(batch_id) ON DELETE CASCADE,
    CONSTRAINT backtest_queue_turn_identity_check
        CHECK ((run_id IS NULL) <> (batch_id IS NULL))
);
CREATE UNIQUE INDEX uq_backtest_queue_standalone ON backtest_queue_turns(run_id)
    WHERE run_id IS NOT NULL;
CREATE UNIQUE INDEX uq_backtest_queue_batch ON backtest_queue_turns(batch_id)
    WHERE batch_id IS NOT NULL;

ALTER TABLE backtest_batches
    ADD COLUMN started_at TIMESTAMPTZ,
    ADD COLUMN completed_at TIMESTAMPTZ;
ALTER TABLE backtest_batch_events
    ADD COLUMN trigger_run_id VARCHAR(36);

-- Preserve queued history during a forward-only upgrade. Active work is
-- reconciled by the worker after its previous owner has been verified stopped.
INSERT INTO backtest_queue_turns (run_id, batch_id)
SELECT run_id, batch_id FROM (
    SELECT r.run_id, NULL::VARCHAR(36) AS batch_id, r.submitted_at AS submitted_at,
        r.run_id AS identity
    FROM backtest_runs r
    WHERE r.status = 'queued' AND r.batch_id IS NULL
    UNION ALL
    SELECT NULL::VARCHAR(36), b.batch_id, b.accepted_at, b.batch_id
    FROM backtest_batches b
    WHERE b.status = 'queued'
) entries
ORDER BY submitted_at, identity;
